export const locationFilterData = [
  { value: '서울' },
  { value: '부산' },
  { value: '대구' },
  { value: '인천' },
  { value: '광주' },
  { value: '대전' },
  { value: '울산' },
  { value: '세종' },
  { value: '경기' },
  { value: '강원' },
  { value: '충북' },
  { value: '충남' },
  { value: '전북' },
  { value: '전남' },
  { value: '경북' },
  { value: '경남' },
  { value: '제주' },
];
