name: Node CI

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Add pnpm to PATH
        run: echo "PATH=$(npm bin -g):$PATH" >> $GITHUB_ENV

      - name: Check pnpm Path
        run: which pnpm

      - run: pnpm install
      - run: pnpm run lint
